### ISSUE TITLE
Issue with using fat/shaded jar

### ISSUE THREAD

**Issue by GiannisMak26** [sheinbergon/dremio-udf-gis#54]
Hi, I am using the following service for Dremio inside a docker-compose file.

```
geodremio:
    image: dremio/dremio-oss:25.1
    container_name: geodremio
    depends_on:
      - geonessie
    networks:
      iceberg_net:
    ports:
      - 7008:9047
      - 7009:31010
      - 7010:32010
    volumes:
      - ./dremio/data:/opt/dremio/data
      - ./dremio/jars:/opt/dremio/jars/3rdparty
```

As I want to use gis functions,I have added the _dremio-udf-gis-0.18.0.jar_ inside the jars subfolder. When restarting the container I get the error
```
2024-11-04 09:21:07 starting dremio
2024-11-04 09:21:07 [2024-11-04T07:21:07.916+0000][0.002s][info][gc,heap] Heap region size: 1M
2024-11-04 09:21:07 [2024-11-04T07:21:07.918+0000][0.004s][info][gc     ] Using G1
2024-11-04 09:21:07 [2024-11-04T07:21:07.918+0000][0.004s][info][gc,heap,coops] Heap address: 0x0000000700000000, size: 4096 MB, Compressed Oops mode: Zero based, Oop shift amount: 3
2024-11-04 09:21:07 [2024-11-04T07:21:07.918+0000][0.004s][info][gc,cds       ] Mark closed archive regions in map: [0x00000007bfe00000, 0x00000007bfe6bff8]
2024-11-04 09:21:07 [2024-11-04T07:21:07.918+0000][0.004s][info][gc,cds       ] Mark open archive regions in map: [0x00000007bfc00000, 0x00000007bfc46ff8]
2024-11-04 09:21:07 Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
2024-11-04 09:21:07     at com.dremio.dac.daemon.DremioDaemon.<clinit>(DremioDaemon.java:36)
2024-11-04 09:21:07 Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
2024-11-04 09:21:07     at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
2024-11-04 09:21:07     at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
2024-11-04 09:21:07     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
2024-11-04 09:21:07     ... 1 more
```

This issue also appears when just mounting the empty ./dremio/jars/ folder. So, without the actual .jar file inside.

**Comment by GiannisMak26** [comment]
In the end I created a custom Dockerfile
```
FROM dremio/dremio-oss:25.2
COPY "dremio-udf-gis-0.18.0.jar" /opt/dremio/jars/3rdparty/
```
and based on that I created my service for Dremio, which solved my issue.

**Comment by sheinbergon** [comment]
I'm glad you suceeeded. Indeed, you initial solution was overriding the jar directories with empty ones, regardless of my extension. Feel free to open additional GH issues if you encounter more problems.
